### ISSUE TITLE
Notification bar interfering with content (iOS)

### ISSUE THREAD

**Issue by Frijon** [kurrycat2004/GOApp#19]
![WhatsApp Image 2020-02-17 at 21 35 29](https://user-images.githubusercontent.com/45359177/74685051-afee5880-51cd-11ea-9b9c-6d489cff399c.jpeg)

**Comment by kurrycat2004** [comment]
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/
Set StatusBarOverlaysWebView to false
